name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-ww-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            ${{ github.workspace }}/ww-ui/.next/cache
          key: ${{ runner.os }}-bun-nextjs-${{ hashFiles('ww-ui/bun.lock') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-bun-nextjs-${{ hashFiles('ww-ui/bun.lock') }}-

      - name: Install Dependencies
        run: |
          cd ww-ui
          bun install --frozen-lockfile

      - name: Run Linter
        run: |
          cd ww-ui
          bun run lint

  build-ww-ui:
    runs-on: ubuntu-latest
    needs: lint-ww-ui
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            ${{ github.workspace }}/ww-ui/.next/cache
          key: ${{ runner.os }}-bun-nextjs-${{ hashFiles('ww-ui/bun.lock') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-bun-nextjs-${{ hashFiles('ww-ui/bun.lock') }}-

      - name: Install Dependencies
        run: |
          cd ww-ui
          bun install --frozen-lockfile

      - name: Build Project
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL || 'http://ww.api.localhost' }}
          NEXT_PUBLIC_WS_URL: ${{ secrets.NEXT_PUBLIC_WS_URL || 'ws://ww.api.localhost/game' }}
        run: |
          cd ww-ui
          bun run build
